# This file contains values from Cookiecutter

default_context:
  project_name: "rang-colorpalette"
  project_description: "Awesome `rang-colorpalette` is a Python cli/package created with https://github.com/TezRomacH/python-package-template"
  organization: "rang-colorpalette"
  license: "GNU GPL v3.0"
  minimal_python_version: 3.9
  github_name: "jptalukdar"
  email: "github@jyotiplaban.com"
  version: "0.1.0"
  line_length: "96"
  create_example_template: "none"
